// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemePlacement.Web.Data;

#nullable disable

namespace SystemePlacement.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707031150_Dev2AddOffreStageDirecte")]
    partial class Dev2AddOffreStageDirecte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SystemePlacement.Web.Models.Administrateur", b =>
                {
                    b.Property<int>("IdAdministrateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_administrateur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAdministrateur"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NiveauAcces")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Standard")
                        .HasColumnName("niveau_acces");

                    b.HasKey("IdAdministrateur");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("administrateurs", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Candidature", b =>
                {
                    b.Property<int>("IdCandidature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_candidature");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCandidature"));

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cv_url");

                    b.Property<DateTime>("DateCandidature")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_candidature");

                    b.Property<DateTime?>("DateReponseEmployeur")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EtudiantIdEtudiant")
                        .HasColumnType("int");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<int>("IdOffre")
                        .HasColumnType("int")
                        .HasColumnName("id_offre");

                    b.Property<string>("LettreMotivation")
                        .HasColumnType("longtext")
                        .HasColumnName("lettre_motivation");

                    b.Property<string>("MessageMotivation")
                        .HasColumnType("longtext")
                        .HasColumnName("message_motivation");

                    b.Property<string>("MessageReponseEmployeur")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("EnAttente")
                        .HasColumnName("statut");

                    b.HasKey("IdCandidature");

                    b.HasIndex("EtudiantIdEtudiant");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdOffre", "IdEtudiant")
                        .IsUnique();

                    b.ToTable("candidatures", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.CandidatureDocument", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_document");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDocument"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("chemin_fichier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_upload");

                    b.Property<int>("IdCandidature")
                        .HasColumnType("int")
                        .HasColumnName("id_candidature");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_fichier");

                    b.Property<long>("TailleFichier")
                        .HasColumnType("bigint")
                        .HasColumnName("taille_fichier");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type_document");

                    b.HasKey("IdDocument");

                    b.HasIndex("IdCandidature");

                    b.ToTable("candidature_documents", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.College", b =>
                {
                    b.Property<int>("IdCollege")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_college");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCollege"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ville");

                    b.HasKey("IdCollege");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("colleges", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DemandeStage", b =>
                {
                    b.Property<int>("IdDemandeStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_demande_stage");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDemandeStage"));

                    b.Property<string>("Competences")
                        .HasColumnType("longtext")
                        .HasColumnName("competences");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("EtudiantIdEtudiant")
                        .HasColumnType("int");

                    b.Property<int>("IdDomaine")
                        .HasColumnType("int")
                        .HasColumnName("id_domaine");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<string>("PeriodeSouhaitee")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("periode_souhaitee");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Ouverte")
                        .HasColumnName("statut");

                    b.HasKey("IdDemandeStage");

                    b.HasIndex("EtudiantIdEtudiant");

                    b.HasIndex("IdDomaine");

                    b.HasIndex("IdEtudiant");

                    b.ToTable("demandes_stage", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DemarcheSuivi", b =>
                {
                    b.Property<int>("IdDemarche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDemarche"));

                    b.Property<DateTime>("DateDemarche")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EtudiantIdEtudiant")
                        .HasColumnType("int");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResponsableIdResponsable")
                        .HasColumnType("int");

                    b.Property<string>("TypeDemarche")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDemarche");

                    b.HasIndex("EtudiantIdEtudiant");

                    b.HasIndex("ResponsableIdResponsable");

                    b.ToTable("DemarchesSuivi");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DomaineEtude", b =>
                {
                    b.Property<int>("IdDomaine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_domaine");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDomaine"));

                    b.Property<bool>("AccepteStagiaires")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("accepte_stagiaires");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<int>("IdCollege")
                        .HasColumnType("int")
                        .HasColumnName("id_college");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.HasKey("IdDomaine");

                    b.HasIndex("IdCollege");

                    b.ToTable("domaine_etudes", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Employeur", b =>
                {
                    b.Property<int>("IdEmployeur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_employeur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmployeur"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("poste");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("")
                        .HasColumnName("telephone");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasDefaultValue("")
                        .HasColumnName("titre");

                    b.HasKey("IdEmployeur");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("employeurs", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Entreprise", b =>
                {
                    b.Property<int>("IdEntreprise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_entreprise");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEntreprise"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("adresse");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("IdEmployeur")
                        .HasColumnType("int")
                        .HasColumnName("id_employeur");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("secteur");

                    b.Property<string>("SiteWeb")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("site_web");

                    b.HasKey("IdEntreprise");

                    b.HasIndex("IdEmployeur")
                        .IsUnique();

                    b.ToTable("entreprises", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Etudiant", b =>
                {
                    b.Property<int>("IdEtudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEtudiant"));

                    b.Property<bool>("CheminementATE")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CvUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("NumeroEtudiant")
                        .HasColumnType("longtext");

                    b.Property<string>("Programme")
                        .HasColumnType("longtext");

                    b.Property<string>("StatutEtudiant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("IdEtudiant");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("etudiants", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Offre", b =>
                {
                    b.Property<int>("IdOffre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_offre");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOffre"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("adresse");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_expiration");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_publication");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("IdEmployeur")
                        .HasColumnType("int")
                        .HasColumnName("id_employeur");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titre");

                    b.Property<string>("TypeOffre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type_offre");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ville");

                    b.HasKey("IdOffre");

                    b.HasIndex("IdEmployeur")
                        .HasDatabaseName("idx_offre_employeur");

                    b.HasIndex("Statut")
                        .HasDatabaseName("idx_offre_statut");

                    b.ToTable("offres", (string)null);

                    b.HasDiscriminator<string>("TypeOffre");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.OffreDomaine", b =>
                {
                    b.Property<int>("IdOffre")
                        .HasColumnType("int")
                        .HasColumnName("id_offre");

                    b.Property<int>("IdDomaine")
                        .HasColumnType("int")
                        .HasColumnName("id_domaine");

                    b.HasKey("IdOffre", "IdDomaine");

                    b.HasIndex("IdDomaine");

                    b.ToTable("offre_domaines", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.OffreStageDirecte", b =>
                {
                    b.Property<int>("IdOffreDirecte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_offre_directe");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOffreDirecte"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext")
                        .HasColumnName("commentaire");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("condtions");

                    b.Property<DateTime?>("DateDebutProposee")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_debut_proposee");

                    b.Property<DateTime?>("DateFinProposee")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_fin_proposee");

                    b.Property<DateTime>("DateProposition")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_proposition");

                    b.Property<int?>("IdCandidature")
                        .HasColumnType("int")
                        .HasColumnName("id_candidature");

                    b.Property<int?>("IdDemandeStage")
                        .HasColumnType("int")
                        .HasColumnName("id_demande_stage");

                    b.Property<int>("IdEmployeur")
                        .HasColumnType("int")
                        .HasColumnName("id_employeur");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<int?>("IdOffreStage")
                        .HasColumnType("int")
                        .HasColumnName("id_offre_stage");

                    b.Property<string>("ReponseEtudiant")
                        .HasColumnType("longtext")
                        .HasColumnName("reponse_etudiant");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Envoyee")
                        .HasColumnName("statut");

                    b.HasKey("IdOffreDirecte");

                    b.HasIndex("IdCandidature");

                    b.HasIndex("IdDemandeStage");

                    b.HasIndex("IdEmployeur");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdOffreStage");

                    b.HasIndex("Statut");

                    b.ToTable("offres_stage_directes", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.ResponsableStage", b =>
                {
                    b.Property<int>("IdResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResponsable"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdResponsable");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("responsables_stage", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom_role");

                    b.HasKey("IdRole");

                    b.HasIndex("NomRole")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("courriel");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_modification");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("derniere_connexion");

                    b.Property<int?>("IdCollege")
                        .HasColumnType("int")
                        .HasColumnName("id_college");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("fr")
                        .HasColumnName("langue");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mot_de_passe_hash");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_utilisateur");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Courriel")
                        .IsUnique();

                    b.HasIndex("IdCollege");

                    b.HasIndex("IdRole");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.OffreEmploi", b =>
                {
                    b.HasBaseType("SystemePlacement.Web.Models.Offre");

                    b.Property<decimal?>("SalaireMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salaire_max");

                    b.Property<decimal?>("SalaireMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salaire_min");

                    b.Property<string>("TeleTravail")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tele_travail");

                    b.Property<string>("TypeContrat")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_contrat");

                    b.HasDiscriminator().HasValue("Emploi");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.OffreStage", b =>
                {
                    b.HasBaseType("SystemePlacement.Web.Models.Offre");

                    b.Property<DateTime?>("DateDebutStage")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_debut_stage");

                    b.Property<DateTime?>("DateFinStage")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_fin_stage");

                    b.Property<int?>("DureeHeuresParSemaine")
                        .HasColumnType("int")
                        .HasColumnName("duree_heures_semaine");

                    b.Property<decimal?>("Remuneration")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("remuneration");

                    b.Property<string>("Session")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("session");

                    b.HasDiscriminator().HasValue("Stage");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Administrateur", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Utilisateur", "Utilisateur")
                        .WithOne("Administrateur")
                        .HasForeignKey("SystemePlacement.Web.Models.Administrateur", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Candidature", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Etudiant", null)
                        .WithMany("Candidatures")
                        .HasForeignKey("EtudiantIdEtudiant");

                    b.HasOne("SystemePlacement.Web.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("IdEtudiant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemePlacement.Web.Models.Offre", "Offre")
                        .WithMany("Candidatures")
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.CandidatureDocument", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Candidature", "Candidature")
                        .WithMany("Documents")
                        .HasForeignKey("IdCandidature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DemandeStage", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Etudiant", null)
                        .WithMany("DemandesStage")
                        .HasForeignKey("EtudiantIdEtudiant");

                    b.HasOne("SystemePlacement.Web.Models.DomaineEtude", "DomaineEtude")
                        .WithMany()
                        .HasForeignKey("IdDomaine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemePlacement.Web.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("IdEtudiant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DomaineEtude");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DemarcheSuivi", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantIdEtudiant");

                    b.HasOne("SystemePlacement.Web.Models.ResponsableStage", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableIdResponsable");

                    b.Navigation("Etudiant");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DomaineEtude", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.College", "College")
                        .WithMany("DomaineEtudes")
                        .HasForeignKey("IdCollege")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Employeur", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Utilisateur", "Utilisateur")
                        .WithOne("Employeur")
                        .HasForeignKey("SystemePlacement.Web.Models.Employeur", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Entreprise", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Employeur", "Employeur")
                        .WithOne("Entreprise")
                        .HasForeignKey("SystemePlacement.Web.Models.Entreprise", "IdEmployeur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Etudiant", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Utilisateur", "Utilisateur")
                        .WithOne("Etudiant")
                        .HasForeignKey("SystemePlacement.Web.Models.Etudiant", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Offre", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Employeur", "Employeur")
                        .WithMany()
                        .HasForeignKey("IdEmployeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employeur");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.OffreDomaine", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.DomaineEtude", "DomaineEtude")
                        .WithMany()
                        .HasForeignKey("IdDomaine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemePlacement.Web.Models.Offre", "Offre")
                        .WithMany("OffreDomaines")
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomaineEtude");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.OffreStageDirecte", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Candidature", "Candidature")
                        .WithMany()
                        .HasForeignKey("IdCandidature")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SystemePlacement.Web.Models.DemandeStage", "DemandeStage")
                        .WithMany()
                        .HasForeignKey("IdDemandeStage")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SystemePlacement.Web.Models.Employeur", "Employeur")
                        .WithMany()
                        .HasForeignKey("IdEmployeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemePlacement.Web.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("IdEtudiant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemePlacement.Web.Models.OffreStage", "OffreStage")
                        .WithMany()
                        .HasForeignKey("IdOffreStage")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Candidature");

                    b.Navigation("DemandeStage");

                    b.Navigation("Employeur");

                    b.Navigation("Etudiant");

                    b.Navigation("OffreStage");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.ResponsableStage", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.Utilisateur", "Utilisateur")
                        .WithOne("ResponsableStage")
                        .HasForeignKey("SystemePlacement.Web.Models.ResponsableStage", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Utilisateur", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.College", "College")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdCollege")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SystemePlacement.Web.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Candidature", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.College", b =>
                {
                    b.Navigation("DomaineEtudes");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Employeur", b =>
                {
                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Etudiant", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("DemandesStage");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Offre", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("OffreDomaines");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.Utilisateur", b =>
                {
                    b.Navigation("Administrateur");

                    b.Navigation("Employeur");

                    b.Navigation("Etudiant");

                    b.Navigation("ResponsableStage");
                });
#pragma warning restore 612, 618
        }
    }
}
