// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemePlacement.Web.Data;

#nullable disable

namespace SystemePlacement.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620025748_Dev2CollegeDomaineInitial")]
    partial class Dev2CollegeDomaineInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SystemePlacement.Web.Models.College", b =>
                {
                    b.Property<int>("IdCollege")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCollege"));

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("actif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ville");

                    b.HasKey("IdCollege");

                    b.ToTable("COLLEGE", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DomaineEtude", b =>
                {
                    b.Property<int>("IdDomaine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_domaine");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDomaine"));

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<int>("IdCollege")
                        .HasColumnType("int")
                        .HasColumnName("id_college");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.Property<bool>("accepteStagiaires")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("accepte_stagiaires");

                    b.HasKey("IdDomaine");

                    b.HasIndex("IdCollege");

                    b.ToTable("DOMAINE_ETUDE", (string)null);
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.DomaineEtude", b =>
                {
                    b.HasOne("SystemePlacement.Web.Models.College", "College")
                        .WithMany("DomaineEtudes")
                        .HasForeignKey("IdCollege")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("SystemePlacement.Web.Models.College", b =>
                {
                    b.Navigation("DomaineEtudes");
                });
#pragma warning restore 612, 618
        }
    }
}
